name = "thompson2026-worker"
main = "signature_worker.js"
workers_dev = true
compatibility_date = "2024-09-08"

[[d1_databases]]
binding = "DB"
database_name = "signature_database"
database_id = "80f203b7-7503-4542-9978-4b064ab0a56d"

[[routes]]
pattern = "thompson2026.com/submit-signature"
zone_name = "thompson2026.com"  # Your domain name here